### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by pilcrowOnPaper** [spences10/sveltekit-mdsvex-starter-blog#68]
Hi,

It seems images are not loading. Not sure if this is a problem with your code or with mdsvex-relative-images.

**Comment by spences10** [comment]
It's my code yeah!

I only realised that the way I'm getting the HTML for the posts doesn't include the `component`.

If you want a way to use relative images check out @matjennings [blog template] it's what I've based my own blog off of.

I'll circle round to this when I work it out, thanks.

[blog template]: https://github.com/mattjennings/sveltekit-blog-template
